### PR TITLE
Added cross navigation functionality.

### PR DESCRIPTION
**Pull request by vivek-30**
@tech4GT sir, Now we can move in both forward direction and backward direction just by using `doubly circular linked list`. 

😂  LOL after few months later think of this idea. Actually it accidentally came into my mind so i thought why not to update it here as well .Bcoz my contribution journey get started from here and you really supported me.

### CODE REVIEW

**Comment by vivek-30** [comment]
see this ` working gif `-

tabSwitching

**Comment by vivek-30** [comment]
may be my next solution will be related to `skip list` just kidding. 😅

**Comment by vivek-30** [comment]
@tech4GT ,sir don't you like this change??

**Comment by tech4GT** [comment]
> @tech4GT ,sir don't you like this change??

Hey @vivek-30 Sorry I missed this! Nice work mate. Merging this now :D

**Comment by vivek-30** [comment]
Oh no problem @tech4GT sir. Thanks BTW 😊

**Pull request merged**
